export default {
    'Accounts of Chemical Research':                                               'Acc. Chem. Res.',
    'Advanced Functional Materials':                                               'Adv. Function. Mater.',
    'Advanced Materials':                                                          'Adv. Mater.',
    'Advances in Optics and Photonics':                                            'Adv. Opt. Photon.',
    'Angewandte Chemie':                                                           'Angew. Chem. Int. Edit.',
    'Applied Optics':                                                              'Appl. Opt.',
    'Applied Pysics B':                                                            'Appl. Phys. B',
    'Applied Physics Letters':                                                     'Appl. Phys. Lett.',
    'Chinese Optics Letters':                                                      'Chin. Opt. Lett.',
    'Chinese Physics Letters':                                                     'Chin. Phys. Lett.',
    'Chinese Science Bulletin':                                                    'Chin. Sci. Bull.',
    'Fronties of Optoelectronics':                                                 'Front. Optoelectron.',
    'IEEE Photonics Technology Letters':                                           'IEEE Photon. Technol. Lett.',
    'IEICE Transactions on Electronics':                                           'IEICE Trans. Electron.',
    'Journal of Applied Polymer Science':                                          'J. Appl. Polym. Sci.',
    'Journal of Leghtwave Technology':                                             'J. Lightwave Technol.',
    'Journal of Non-crystalline Solids':                                           'J. Non-Cryst. Solids',
    'Journal of Optics':                                                           'J. Opt. A',
    'Journal of Physics Chemistry C':                                              'J. Phys. Chem. C',
    'Journal of the American Chemical Society':                                    'J. Am. Chem. Soc.',
    'Journal of The Optical Society of America A-optics Image Science and Vision': 'J. Opt. Soc. Am. A',
    'Journal of The Optical Society of America B-optical Physics':                 'J. Opt. Soc. Am. B',
    'Lab on a Chip':                                                               'Lab Chip',
    'Laser & Photonics Reviews':                                                   'Laser & Photon. Rev.',
    'Microfluidics and Nanofluidics':                                              'Microfluid. Nanofluid.',
    'Nano Letters':                                                                'Nano Lett.',
    'Optics Communications':                                                       'Opt. Commun.',
    'Optics Express':                                                              'Opt. Express',
    'Optics Letters':                                                              'Opt. Lett.',
    'Physica E-low-dimensional Systems & Nanostructures':                          'Physica E',
    'Physical Review A':                                                           'Phys. Rev. A',
    'RSC Advance':                                                                 'RSC Adv.',
    'Scientific Reports':                                                          'Sci. Rep.',
    'Sensors and Actuators B-chemical':                                            'Sensor Actuat. B-chem.',
    'Superconductor Science & Technology':                                         'Supercond. Sci. Tech.'
}

